---

- name: Modify default .zshrc
  ansible.builtin.blockinfile:  # noqa var-spacing
    insertbefore: BOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK -- Common"
    path: "{{ ansible_user_dir }}/.zshrc"
    block: |
      # WARNING: This file is managed by ansible
      [[ -f ~/.zprofile ]] && source ~/.zprofile

      # Stop zsh themes from complaining
      export TERM="xterm-256color"

      # Why not the default, though?
      export EDITOR=/usr/bin/vim

      # Path to my oh-my-zsh installation.
      export ZSH="{{ ansible_user_dir }}/.oh-my-zsh"

      # Tells 'less' not to paginate if less than a page
      export LESS="-eirMXF"

      # Fix bindkeys for some reason
      bindkey '\e[4~' end-of-line
      bindkey '\e[1~' beginning-of-line

      # Autocompletions #############################################################
      autoload -U compinit && compinit
      ###############################################################################

      # Hook for desk activation ####################################################
      [ -n "$DESK_ENV" ] && source "$DESK_ENV" || true
      ###############################################################################

      # Add local bin directory
      export PATH={{ ansible_user_dir }}/bin:${PATH}

      # Setup up direnv #############################################################
      eval "$(direnv hook zsh)"
      ###############################################################################
