---

- name: git
  src: https://github.com/mtik00/ansible-role-git.git
- name: dotfiles
  src: https://github.com/mtik00/ansible-role-dotfiles.git
- name: home_folders
  src: https://github.com/mtik00/ansible-role-home-folders.git
